<?php
$lang = array(
"title"		=> "ब्लाँगप्रेस यूआरएल सार्टनर",
"submit"		=> "छोटा करें",
"version"		=> "१.०.०",
"copyright"		=> "&copy २०१४ ब्लाँगप्रेस टीम | भोजपुरीखोज डाँट काँम की इकाईं",
"output"			=> "ये रहा आपका छोटा वेब पता:",
"longurl"		=> "कृपया एक वेब पता(यूआरएल) लिखें.",
"Do not edit this file without buy this script-Script is owened by Bhojpurikhoj.Com"
);
?>
