<?php
$lang = array(
"title"		=> "ब्लाँगप्रेस यूआरएल सार्टनर",
"submit"		=> "छोटा कईल जाव",
"version"		=> "१.०.०",
"copyright"		=> "&copy २०१४ ब्लाँगप्रेस टीम | भोजपुरीखोज डाँट काँम की इकाईं",
"output"			=> "हो गईल छोट वेब पता:",
"longurl"		=> "एगो वेब पता लिखीं.",
"Do not edit this file without buy this script-Script is owened by Bhojpurikhoj.Com"
);
?>
