<?php
$lang = array(
"title"		=> "Blogpress Url Shortner",
"submit"		=> "Shrink",
"version"		=> "1.0.0",
"copyright"		=> "&copy 2014 Blogpress | Powered by Bhojpurikhoj.Com",
"output"			=> "Here's the short URL:",
"longurl"		=> "Please enter your long url to shrink.",
"Do not edit this file without buy this script-Script is owened by Bhojpurikhoj.Com"
);
?>
